# Generated by Django 4.2.4 on 2023-09-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_user_city_user_door_no_user_state_user_street_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=128, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('door_no', models.CharField(blank=True, max_length=128)),
                ('street', models.CharField(blank=True, max_length=128)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('state', models.CharField(blank=True, max_length=128)),
                ('zip_code', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='door_no',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
        migrations.RemoveField(
            model_name='user',
            name='street',
        ),
        migrations.RemoveField(
            model_name='user',
            name='zip_code',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('CUSTOMER,', 'Customer'), ('ADMIN', 'Admin'), ('DELIVERY PARTNER', 'Delivery Partner')], max_length=128),
        ),
    ]
