# Generated by Django 4.2.4 on 2023-09-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customertable_remove_user_city_remove_user_door_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customertable',
            name='city',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='customertable',
            name='door_no',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='customertable',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customertable',
            name='phone_number',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customertable',
            name='state',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='customertable',
            name='street',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='customertable',
            name='zip_code',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
