# Generated by Django 4.2.4 on 2023-09-23 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_customertable_city_alter_customertable_door_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertable',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
