# Generated by Django 4.2.4 on 2023-09-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_alter_user_email_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('ADMIN', 'Admin'), ('DELIVERY PARTNER', 'Delivery Partner')], max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='vehicle_type',
            field=models.CharField(choices=[('TATA ACE', 'Tata Ace'), ('TATA 407', 'Tata 407'), ('PICKUP', 'Pickup'), ('DOST', 'Dost'), ('SUPER ACE', 'Super Ace'), ('8FT', '8FT'), ('3 WHEELER', '3 Wheeler'), ('3 WHEELER ELECTRIC', '3 Wheeler Electric')], max_length=128, null=True),
        ),
    ]
