# Generated by Django 4.2.4 on 2023-09-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_alter_user_user_type_alter_user_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='transit',
            field=models.IntegerField(default=0),
        ),
    ]
