# Generated by Django 4.2.4 on 2023-09-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleCapicityTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('TATA ACE', 'Tata Ace'), ('TATA 407', 'Tata 407'), ('PICKUP', 'Pickup'), ('DOST', 'Dost'), ('SUPER ACE', 'Super Ace'), ('8FT', '8FT'), ('3 WHEELER', '3 Wheeler'), ('3 WHEELER ELECTRIC', '3 Wheeler Electric')], max_length=128)),
                ('vehicle_space', models.CharField(max_length=128)),
            ],
        ),
    ]
