# Generated by Django 4.2.4 on 2023-09-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryAdmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclecapicitytable',
            name='vehicle_space',
        ),
        migrations.AddField(
            model_name='vehiclecapicitytable',
            name='vehicle_length_feet',
            field=models.FloatField(default=3.5),
        ),
        migrations.AddField(
            model_name='vehiclecapicitytable',
            name='vehicle_load_capacity_kg',
            field=models.FloatField(default=500),
        ),
    ]
