# Generated by Django 4.2.4 on 2023-09-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryAdmin', '0002_remove_vehiclecapicitytable_vehicle_space_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclecapicitytable',
            name='no_of_items',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='vehiclecapicitytable',
            name='price_per_km',
            field=models.FloatField(default=50),
        ),
    ]
