# Generated by Django 4.2.4 on 2023-09-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(choices=[('FURNITURES', (('SOFA (SINGLE)', 'Sofa (Single)'), ('SOFA (DOUBLE)', 'Sofa (Double)'), ('SOFA (3 SEATER)', 'Sofa (3 Seater)'), ('SOFA (4 SEATER)', 'Sofa (4 Seater)'), ('BED (SINGLE)', 'Bed (Single)'), ('BED (DOUBLE)', 'Bed (Double)'), ('COT (FOLDING)', 'Cot (Folding)'), ('MATTRESS (SINGLE)', ''), ('MATTRESS (DOUBLE)', ''), ('DINING TABLE CHAIRS', ''), ('OFFICE CHAIRS', ''), ('PLASTIC CHAIRS', 'Plastic Chairs'), ('DRESSING TABLE', 'Dressing Table'), ('DINING TABLE', 'Dining Table'), ('COMPUTER TABLE', 'Computer Table'))), ('APPLIANCES', (('TV', 'TV'), ('AC', 'AC'), ('FAN', 'Fan'), ('FRIDGE', 'Fridge'), ('WASHING MACHINE', 'Washing Machine'), ('GAS STOVE', 'Gas Stove'), ('MICROWAVE OVEN', 'Microwave Oven'), ('WATER PURIFIER', 'Water Purifier'))), ('VEHICLES', (('BIKE', 'Bike'), ('SCOOTER', 'Scooter'), ('BICYCLE', 'Bicycle')))], max_length=128)),
                ('item_weight_kg', models.FloatField(default=20)),
                ('item_size', models.FloatField(default=2)),
            ],
        ),
    ]
