# Generated by Django 4.2.4 on 2023-09-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoveEaseAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemstable',
            name='item_name',
            field=models.CharField(choices=[('FURNITURES', (('SOFA (SINGLE)', 'Sofa (Single)'), ('SOFA (DOUBLE)', 'Sofa (Double)'), ('SOFA (3 SEATER)', 'Sofa (3 Seater)'), ('SOFA (4 SEATER)', 'Sofa (4 Seater)'), ('BED (SINGLE)', 'Bed (Single)'), ('BED (DOUBLE)', 'Bed (Double)'), ('COT (FOLDING)', 'Cot (Folding)'), ('MATTRESS (SINGLE)', 'Mattress (Single)'), ('MATTRESS (DOUBLE)', 'Mattress (Double)'), ('DINING TABLE CHAIRS', 'Dining Table Chairs'), ('OFFICE CHAIRS', 'Office Chairs'), ('PLASTIC CHAIRS', 'Plastic Chairs'), ('DRESSING TABLE', 'Dressing Table'), ('DINING TABLE', 'Dining Table'), ('COMPUTER TABLE', 'Computer Table'))), ('APPLIANCES', (('TV', 'TV'), ('AC', 'AC'), ('FAN', 'Fan'), ('FRIDGE', 'Fridge'), ('WASHING MACHINE', 'Washing Machine'), ('GAS STOVE', 'Gas Stove'), ('MICROWAVE OVEN', 'Microwave Oven'), ('WATER PURIFIER', 'Water Purifier'))), ('VEHICLES', (('BIKE', 'Bike'), ('SCOOTER', 'Scooter'), ('BICYCLE', 'Bicycle')))], max_length=128),
        ),
    ]
