# Generated by Django 4.2.4 on 2023-10-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoveEaseAdmin', '0004_couponcodetable_orderreceived'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderreceived',
            name='order_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderreceived',
            name='order_taken',
            field=models.IntegerField(default=0),
        ),
    ]
