# Generated by Django 4.2.4 on 2023-10-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoveEaseAdmin', '0005_orderreceived_order_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderreceived',
            name='delivery_person_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='orderreceived',
            name='delivery_person_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='orderreceived',
            name='delivery_person_ph_no',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='orderreceived',
            name='delivery_preson_account_id',
            field=models.IntegerField(null=True),
        ),
    ]
