# Generated by Django 4.2.4 on 2023-10-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoveEaseAdmin', '0006_orderreceived_delivery_person_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderreceived',
            name='alloted_to',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderreceived',
            name='customer_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='orderreceived',
            name='customer_review',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='orderreceived',
            name='rejection_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='orderreceived',
            name='status',
            field=models.CharField(choices=[('ORDERED', 'Ordered'), ('ORDER CONFIRMED', 'Order Confirmed'), ('READY FOR PICKUP', 'Ready For Pickup'), ('PICKING UP', 'Picking Up'), ('TRANSIT', 'Transit'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='ORDERED', max_length=128),
        ),
    ]
