# Generated by Django 4.2.4 on 2023-10-05 06:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoveEaseAdmin', '0007_orderreceived_alloted_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderreceived',
            name='pickup_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 5, 11, 53, 15, 149127)),
        ),
    ]
