# Generated by Django 4.2.4 on 2023-10-05 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoveEaseAdmin', '0008_orderreceived_pickup_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderreceived',
            name='pickup_time',
            field=models.TimeField(default=datetime.datetime(2023, 10, 5, 12, 36, 24, 943030)),
        ),
    ]
