# Generated by Django 4.2.4 on 2023-10-05 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoveEaseAdmin', '0009_alter_orderreceived_pickup_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderreceived',
            name='rejected',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderreceived',
            name='pickup_time',
            field=models.TimeField(default=datetime.datetime(2023, 10, 5, 13, 16, 53, 341305)),
        ),
        migrations.AlterField(
            model_name='orderreceived',
            name='status',
            field=models.CharField(choices=[('ORDERED', 'Ordered'), ('ORDER CONFIRMED', 'Order Confirmed'), ('READY FOR PICKUP', 'Ready For Pickup'), ('PICKING UP', 'Picking Up'), ('TRANSIT', 'Transit'), ('COMPLETED', 'Completed')], default='ORDERED', max_length=128),
        ),
    ]
