# Generated by Django 4.2.4 on 2023-10-05 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoveEaseAdmin', '0010_orderreceived_rejected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderreceived',
            name='pickup_time',
            field=models.TimeField(default=datetime.datetime(2023, 10, 5, 13, 17, 55, 850663)),
        ),
        migrations.AlterField(
            model_name='orderreceived',
            name='status',
            field=models.CharField(choices=[('ORDERED', 'Ordered'), ('ORDER CONFIRMED', 'Order Confirmed'), ('READY FOR PICKUP', 'Ready For Pickup'), ('PICKING UP', 'Picking Up'), ('TRANSIT', 'Transit'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='ORDERED', max_length=128),
        ),
    ]
