# Generated by Django 4.2.4 on 2023-10-05 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoveEaseAdmin', '0011_alter_orderreceived_pickup_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderreceived',
            name='pickup_time',
            field=models.TimeField(default=datetime.datetime(2023, 10, 5, 17, 9, 19, 956246)),
        ),
    ]
