# Generated by Django 4.2.4 on 2023-10-05 22:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoveEaseAdmin', '0012_alter_orderreceived_pickup_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderreceived',
            name='payment_mode',
            field=models.CharField(choices=[('NET BANKING', 'Net Banking'), ('UPI', 'Upi'), ('CREDIT CARD', 'Credit Card'), ('DEBIT CARD', 'Debit Card'), ('COD', 'Cash on Delivery')], default='COD', max_length=128),
        ),
        migrations.AlterField(
            model_name='orderreceived',
            name='pickup_time',
            field=models.TimeField(default=datetime.datetime(2023, 10, 6, 4, 11, 18, 40340)),
        ),
    ]
