# Generated by Django 4.2.4 on 2023-10-06 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoveEaseAdmin', '0013_orderreceived_payment_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderreceived',
            name='payment_mode',
            field=models.CharField(choices=[('NET BANKING', 'Net Banking'), ('UPI', 'Upi'), ('CARD', 'Card'), ('COD', 'Cash on Delivery')], default='COD', max_length=128),
        ),
        migrations.AlterField(
            model_name='orderreceived',
            name='pickup_time',
            field=models.TimeField(default=datetime.datetime(2023, 10, 6, 16, 17, 7, 784130)),
        ),
    ]
