# Generated by Django 4.2.4 on 2023-10-06 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoveEaseAdmin', '0015_orderreceived_customer_cancellation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderreceived',
            name='refund_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderreceived',
            name='pickup_time',
            field=models.TimeField(default=datetime.datetime(2023, 10, 6, 16, 53, 4, 978686)),
        ),
    ]
