# Generated by Django 4.2.4 on 2023-10-08 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoveEaseAdmin', '0016_orderreceived_refund_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderreceived',
            name='unique_order_id',
            field=models.CharField(default='MOVEEASE-YYYYMMDD-HHMM-account_id', max_length=128),
        ),
        migrations.AlterField(
            model_name='orderreceived',
            name='pickup_time',
            field=models.TimeField(default=datetime.datetime(2023, 10, 8, 19, 36, 50, 664399)),
        ),
    ]
