# Generated by Django 4.2.4 on 2023-10-08 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoveEaseAdmin', '0017_orderreceived_unique_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderreceived',
            name='order_cancel_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='orderreceived',
            name='order_completed_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='orderreceived',
            name='order_placed_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='orderreceived',
            name='pickup_time',
            field=models.TimeField(default=datetime.datetime(2023, 10, 8, 19, 57, 26, 284918)),
        ),
        migrations.AlterField(
            model_name='orderreceived',
            name='unique_order_id',
            field=models.CharField(default='MOVEEASE-YYYYMMDD-account_id', max_length=128),
        ),
    ]
