# Generated by Django 4.2.4 on 2023-10-09 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoveEaseAdmin', '0020_rename_order_placed_time_orderreceived_order_placed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponcodetable',
            name='validity_per_account',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='couponcodetable',
            name='max_discount_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='couponcodetable',
            name='min_billing_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='couponcodetable',
            name='offer_percent',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='orderreceived',
            name='pickup_time',
            field=models.TimeField(default=datetime.datetime(2023, 10, 9, 14, 29, 9, 632847)),
        ),
    ]
