# Generated by Django 4.2.4 on 2023-10-09 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoveEaseAdmin', '0021_couponcodetable_validity_per_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponCountTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_id', models.IntegerField()),
                ('customer_acc_id', models.IntegerField()),
                ('count_per_user', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='orderreceived',
            name='pickup_time',
            field=models.TimeField(default=datetime.datetime(2023, 10, 9, 15, 18, 34, 775964)),
        ),
    ]
