# Generated by Django 4.2.4 on 2023-10-09 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoveEaseAdmin', '0023_couponcodetable_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderreceived',
            name='pickup_time',
            field=models.TimeField(default=datetime.datetime(2023, 10, 9, 16, 50, 22, 385431)),
        ),
    ]
