# Generated by Django 4.2.4 on 2023-10-09 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoveEaseAdmin', '0024_alter_orderreceived_pickup_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcodetable',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='orderreceived',
            name='pickup_time',
            field=models.TimeField(default=datetime.datetime(2023, 10, 9, 22, 7, 42, 229942)),
        ),
    ]
