# Generated by Django 4.2.4 on 2023-10-10 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoveEaseAdmin', '0025_alter_couponcodetable_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderreceived',
            name='otp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderreceived',
            name='pickup_time',
            field=models.TimeField(default=datetime.datetime(2023, 10, 10, 11, 27, 13, 520059)),
        ),
    ]
