# Generated by Django 4.2.4 on 2023-10-10 06:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoveEaseAdmin', '0026_orderreceived_otp_alter_orderreceived_pickup_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderreceived',
            name='otp',
            field=models.CharField(default='000000', max_length=128),
        ),
        migrations.AlterField(
            model_name='orderreceived',
            name='pickup_time',
            field=models.TimeField(default=datetime.datetime(2023, 10, 10, 11, 30, 0, 793710)),
        ),
    ]
