# Generated by Django 4.2.4 on 2023-10-10 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoveEaseAdmin', '0027_alter_orderreceived_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderreceived',
            name='pickup_time',
            field=models.TimeField(default=datetime.datetime(2023, 10, 10, 11, 32, 44, 577643)),
        ),
    ]
