# Generated by Django 4.2.4 on 2023-10-13 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoveEaseAdmin', '0028_alter_orderreceived_pickup_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositiveWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive_words', models.CharField(default='GOOD', max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='orderreceived',
            name='pickup_time',
            field=models.TimeField(default=datetime.datetime(2023, 10, 13, 11, 44, 1, 942937)),
        ),
    ]
